services:
  Cwd\PowerDNSClient\PowerDNSClientFactory: ~

  Cwd\PowerDNSClient\PowerDNSClient:
    public: true
    factory:   'Cwd\PowerDNSClient\PowerDNSClientFactory:createClient'
    arguments:
      - '%cwd_power_dns_client.uri%'
      - '%cwd_power_dns_client.api_key%'
      - '%cwd_power_dns_client.default_server%'
      - '@annotation_reader'