build:
  nodes:
    analysis:
      project_setup:
        override:
        - 'true'
      tests:
        override:
        - php-scrutinizer-run
        -
          command: phpcs-run
          use_website_config: true
    tests: false
filter:
  excluded_paths:
  - 'tests/*'
checks:
  php: true
coding_style:
  php: {  }