version: '2'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - .:/var/www/app
            - /var/lib/mysql
            - .docker/mysql/pdns.sql:/docker-entrypoint-initdb.d/pdns.sql  
        environment:
            MYSQL_PASSWORD: dev
            MYSQL_USER: dev
            MYSQL_DATABASE: project
            MYSQL_ALLOW_EMPTY_PASSWORD: 1

    php:
        image: dockerhub.cwd.at/docker/php/fpm-xdebug:8.3
        working_dir: /var/www/app
        user: "$USERID"
        volumes:
            - .:/var/www/app
        environment:
            SYMFONY_DEPRECATIONS_HELPER: weak
            PHP_XDEBUG_ENABLED: 1
            PHP_IDE_CONFIG: serverName=docker.local
            XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9000 remote_connect_back=0

    powerdns:
        image: dockerhub.cwd.at/docker/powerdns:0.3
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: dev
            MYSQL_PASS: dev
            MYSQL_DB: powerdns
        ports:
            - 8000:80
              
                    
